input = "neswsesewswswswswswneeswswswswwwnwsw
nenesenenwneenwnwweneswnenenenwnw
wewnesesweswsenwnwnwsww
eeneswneewneseneeeseeweeesenwe
nwnenenenenenewnwnesenwnwnenenenenenwnese
nwwenwswwnwwwenwnwwnwnwwwnwnwsew
nwnwnenwnwnwnwnwnwswnwnenwswnwnwnenenwne
swsesenweseswseseswswnwswswswseesesesw
nweneneswnenenenenwnenwnwswswnwnwwswsenwne
wnwnwenwnwnwnwnwsewnwnenwnwwwsw
senwewwsewswswnwseswsenwswswsewnenww
nenwnesenwnenwnwnwnenwenwswnwnewnwswnw
neneswwsesenwsesewnenenenenenewenwne
weneneeneneneneeene
ewnwsenwwwwnwnewwneswnwsenwwnwsesww
neenwnwnenenenwwnwnwnenenenenwswnwnenwnwe
wwnwswwwnwwnwwwwwwnewnw
neneneneeneneneneneneswnenenenenenenene
nwwnenwnenwnenenenenesenenwnenenwnwnwne
nenenwsenwsesesenwwnwneenesewnenwnene
nenenewneneeneneneneeseneswnenenenwnene
seseenwewseswsese
seseeseseseseswsesesesesesesesenesesese
sewswswnwswswswswwew
wseswnwnwnwnenewnwnwwnwwnwnwnewnwsw
neeeenenwneeeeeeswneneneeneee
swnwnwnwnwnwnenenwnwewnwnwnenenwnwneenwne
swswsweswseeswseswneswwswseswnwsesww
swnewwnewwweewwwwnwsewwwww
eneswswwewwwswswesewwswswnwwe
eswnweeeeeneeeeeeesweeee
wswswnweswwswnewswseswswswswswswswe
nwewnwwwwnwwwwneswswwwwwnew
nwnwnwnwnwwnwnwwenwnwnwnwsenwnwnwswnwnw
swswnewswswswswwswswwwwweseswswswnww
swneewswswswwswnwnwswwnwwsenwswese
nenenenwswnenenwnenenwnwnwnenenwnenenwne
nwnwnwnwwneswswenwenwenwnwnwnww
neneseswnenwneneneneneenesw
nweswswnwsewswnwwseeseneswnwneene
wwwwswwwnwswwwswsewewwswwsw
wewswwewswswswnweswwswswsweswwsw
sesesesesesewseswsesesesesesenesenesesw
wsweeneeeeneeeene
eseeeeeeeeeeeenweseseseee
wesesewswnesewneeswseewsewnwesesw
seweeneneeweeeneneeeneneeseew
wswseswswwenwswwwswwwsw
eweweeewseneswseenweswnweswene
wwswwwwwwwsewnewswwwwswwww
swseewseneeneswswnewneesewsenwese
sewwwwwwwnwwwnwwww
seseneeseseeenwsesweseeeseswsesesese
neenewnwneneeeneseneneeneseeneneene
nwenwwwswnwwwwwnw
nwseswseseswneseeswneswswneswswsewswse
swswswwswwswwswnewwswwswwseswswe
wnwwnwwnwnwsenwnwnwwnww
swswnwseseseswsesesesewenesewenwsese
eseseesenweeseswseseenwee
nenwseseneeeeeenweseenweweee
swsweseswnwswswswswswswseswswswneseswsw
wnewenesenesweswwnwwseesesesee
wsesesesewseneseseesesesesesesesesesese
seeseeseeeseeswsweesesenwneenwnw
nwwnwnwnwsenwnwwswnwnwsenweswnwnwnwnwnee
esenenenenenenenenenewnewnenenenenene
eswswswswswwswswswwnwswswswswswwswsw
nwnenwnwenwesenwsewsenwwsewswnwsenw
nwnwnwwnwnwnwwnewwwnenwsenwnwwnwwsw
weeseswwenwnwwewwwwnwseenesw
wwswswswwswwwnwwwswsewswwsw
ewsewweswwwewwwwwwnwenwnw
eenwnwnewneweneswseenewseswwsesw
neenenenenenenewwneneseneneneeneene
seswnwswswseswswnwnwseseseeswseswswseswsesw
seseneswseewsesweseseseseseswnwsesesese
nwnwnwnwnwwnwnwnwnwnwenwnwwnwnwwnwnw
seswswsenwwseneseseseswswneseswnesesesesese
eseeseeeeeenweenwesweneenee
nwneswnwnwnwnwnwswneeseswenwswnwnwnww
swsesweswseswswnwswswswswswswnweswswsw
neseseesweseeeseeesewneeewsene
neneswnewneneswseswneswnenw
seweeweswwwnenesewwwnwnewsew
swwweswswswwswswwswswnwswswwswswsw
wneneenenesenewsenenwneswnewneenenw
senwnewnwnwnwnwnwnwwnwswwenwsesenwnwne
wwwwwwnwswsewwwwwwwsw
neneweneeeeenenweneeeeeenwsese
swswsweswswswswswswswswnwseseswswseseswsw
swswswswseswswnwswswseswswnwswneswsee
nwewnenwseneneswsenenenewnenwnesenwnenw
eseswnwswswseneswseseswswseeswswswwsw
seseeeseseseweneeseeeesesesesesese
eewnweswswsweeenenwwnwse
wwswwwswwsewwswnwenwnwswswwwesw
wwewwwwwwwswwwnewwwwww
nwenwwnwnwnwnwneseswnwnwnwnwnwnwnene
nwwnewnwnwwnwnwnwwnwnwsenwwwnwnwww
sewswneswseeswseneseswswswsewneseswnw
newneswswwwwsweswswenesesewneswsw
nwnewwwwwnwswwseswwwwnwwseese
wwwwnewwwwwwenewswwwwwsww
eseeeeeewseneswswseweeneesesee
nwnwnwswnenwnewnwenwnwnwsenwenenwnwwnwne
swseswseswsenesewswseseswswswseswsesese
swswsesesesweswnesesesewsese
eeweeeeseseeesee
swnwnwnwnenwnwnwnwnwnwnwnwnwnwwnwsenenw
nwwnwwwnwswwwwwwnwwewwewww
swnenenenenenenenenenenenenenenenenene
swswneswswswswswseswswnwswswswswswewsw
nwneswnwnenwnwnwnenwnenenenenwnwnenwnwenw
nwnwnwnenwnwnwnenwnwnwnwnenwsenwnwnwnwwnw
wnwnwwnwswwwsenwnwnwnwnwwnewseeww
nwenwnwnwenwnwwnwnwwsenwnwswwwnwnwnw
eeweeseseeeseseeseseseseseese
neeenesewswsweeneenweesenenwswesw
nwwnwnwnwewwnwnwnwwnwwnwnwnwewnwnw
wnwneswwwswwwewwwwswwsewwswne
nwnwsesenenwnenwswseswnenwwnwnenwnwnwnene
nenenwnwnewnwswnwnwnenwneneneeneenww
wwnwswnwnwnwnwnwswswsenwnwenwneesee
nenwnwnwnwnenenwnenwnesenenenenenwnwsenw
swseswswseswseseseswneseswswswseswswswsw
swswsweneswnwwsweswswswswswswswnesw
wnwwwwwwwwswwwewnewwnwwwwse
nwnenenenenenwnwnwwnwenwnwwsenesesenwnw
nenwneeeeeswswneeeeeneeeneswnee
nenwnwnwnwnwnwsenwwnwnwnwwnwnwnwsenesenw
nwnwwnwwswwwnwwnwwnwsewwnwnewnw
wnwwwwenwseswnwswewnww
ewwnwwwswwnwwnww
nwnenwnenenenenenenenewnesenene
sesesesweenwsenwenwsenweesenwenwnw
neneeeeswenwneeswsenwenenenenenenee
seeesenwswwesenwsesenwseseswesenesee
nenwnwnenwswnenwnwsenwnesenwnwnwnwnenenw
eeeeeeeeeeesweenwswne
esesweswnwsenweeesesesenweeesww
eseseeseseseseseweeseeeseesee
swnenenenwnwnesenenewnwneeneneneenenesw
neneneenenenenewneneneseneneneneeewse
wnwnwnwnwenwnwwewswwwwwnwsewwwe
neneeneneneneneneneneneswne
seswswseseeswswnwseseneswswseseseseswsese
wswnwswweneweenwwswswneswswwseswne
eswwwswswneswwswwnwwwenwwwswsewsw
wswswswswenwnwnwswswswswswswseswneeswe
wwwwwswswwwenenwnwnwwnenwsesww
wseweeenwnewneneneneseeneneenwswse
senwwnenwnwnewseswwwsewswnewneene
nenwnwnweneneenesesweneneneneneneswsw
swseswswswswwswswswneseswseswsewswswnesesw
enewnenwnenenenwsenenwnwnwnenenwseswene
wwnewwwswwwwwwwwwswsewwww
wsenwnwnewnwnwnwnwnwnwnwnwnwnwnwwnwnw
wenwnwwwwnwwsenwneswsewwsewnwnw
neenewneneeeneeee
neseswnwswswnwnwseseswseewseseneseswseswsw
nenenewwnenenewneeenenenweswsene
seeeeesesesweeenweesenwseeseswe
swesenweseewseeseeswswesenwenenewne
seseseseseseeeswnwswne
wwwwwwwwwwnwnwsewnwwwwsewe
nenwnwneeswnwnwenwswswnwnwnwswnwnwnwnwnwnw
swswswesewswswseswswswseswswseswswsw
neneenenenenenenenenenewnenenenenenene
wneseenenwnwwswseswswwnewnwwwww
nwnwnwwnwnwweseneswwnwseenwnwnwwnwsw
nwnwsenwnwnenwnwnwnwsenwnwnwnwsenwnwnewnwnw
wsewneeneneneneneneeeneswe
nenwnwnweweswneswne
eseeeeeseeeeeeeeeweewee
newnwswnenwneneneneeneweswnenwnee
wwnwwwwwwnwwnwnwnwsewnwwwww
wwnwwnwwnwswwnwwwwnwwwnweww
neseseseseseswsesesesesesesesesesesesesw
nenwnwnwnwswwnwwnwnwwnwswnwnwnwwnwnwe
neenweeeeeeeeeeneeswseeeswe
swswswswwswswnwswswsesweswswnwswwsw
wnwsenwwnwwnwnwnwnwnwnenwnwnwnwnwnwnw
seswnwswenesesewneswnwsewsesesenenesw
eneewnweseswweeenee
neeneswneswsweswwnenweee
eeseesenewneeeneneswenewne
swnwsewnwnwneweswnenwneneseesenwwsesw
wseewswwnenwswswseesweseneswnwswese
seseseseseswsesesewswseseswseseseseswnene
seseswsesesewnenewseneswnesew
wswseswnwwwwewwwwwswwwwswww
nwnwwnwnwnwnwnwnwnwnwwnwnwnwnwnwenwe
nenwsesenenenenenwnwnwnenwsenenwnwnenwnewne
nwnenenwnenwnwswnewnwnwenenwnwnwnwnene
neseswswnwnwnwneswsweneseseswswnwnewesw
swwsewwwewswswnwwswswwnwsw
neweeswneeeneeneneenwswneseewnw
sewswwweseenwneesewwsewswneee
wwwnwnwswwwwwwnenwnwnwnwnwnwwnw
wwwswwwwwwwwnewwwwneswwsew
nwseswswswneswenesewseeswswswswswnenw
enwswseeeseseswesesesesesenesenwseese
nenenwneswnwnwneneenwnwnweswnenwnwnwnwnw
nwswweneeeeeeeeeeneeeswnese
sweseseseseeeswenwneeeeese
seswswseeswsesewesweswswsesesesenwnwsesw
eenwnewesesewseneeswseewsweenwe
seseswnwwwnewwswweswnwwnewwesw
eeeeeeseseseeseweeeeeeseenew
weseeneswenwewe
swswsesenwseswseseswseneesewswsesesesese
seswseseswswswseseswswswneswswswsesesw
swwswwsewswwswnwwsesweswnwsenwnwnee
eneweeneneneeeeeeee
sesesesenesewsesese
nwnwnenwnewnenwnwnwsenenwnenwnwnwnwnwne
swneswseseswswnwseseseseseswwseswswsese
swswsewnewswwswswswswnenwwwneswsewsw
nwswswsweneseseswseneswseseswnweswew
swseswswswseswswswswseseswseswnesesw
nenwnenenwenwnwnwnwnenenwwwenwnenwne
swwnwnwwwwnwewwnwnwnwnwnwwnw
esenwneswnenwneeswwswenwseneseeenw
eeeswsenwweneenenenesenenewsenenesew
wwswsenwwwnewwewwswwswwwwne
wswesweenewswswnwswsweswnwnwswswe
swswseneswswswswsewswsw
wnenenenewneenesenwwseeneneswne
seeseseseeseenweewseseneseseeseese
seseesesewseseseseseesweseneseesese
swnwnwneseswswswswwe
senwnwnwnwnwnwswnwwnwnenenwwnwnwnwwnww
wwwsenwewwswswwnwsewwewswsww
swwswswswneseseseswsewseswswneswswsesw
seseeeseseseeseseseseseesewesesese
seseeeseweeneseewseeeeeseee
nesenwnwnenenenenwnwnwnwnwnwnenenwsenw
seseseeesesesenweseseeswseseseenese
swswswswswswswseswswswswswswswnenwswswswsw
senwwswwswswwswswwswswswneswsweswsw
swesenwswseswnwnwseseswseswswsweseesesw
wwswswwwswwweswwswswwswswwswsw
swewsweswswewnwwnewewwsewnwswww
wnewseseswswnwswwnwnwwnwswseswseeew
swsenwseseswswseneswswseseseswseseseswsw
swswwwewswswswwwweswwwwesww
swswswneeswnwswswswswswweswswswswswnwsw
enweneeseeneneswswsewneneneeeene
wswwswnwwwewwnwswesewswseenwe
sesesesweeeseeewsenwseseeeseeee
swswswswnwswswswswswswswsweswswseswswswsw
seseewseseeseesesesesesesesesenwsese
eweeseweeneeeeneeeeeeeeese
eeeeeeeeeeeeeeenweeeesw
nwswswswwwwwwwswswweswwwswswsw
weswswnwswweswnwnwneswsenesewwenesw
enweeseeseeneseseseewseeseeesesee
nwnwnwnwnenwwnwnwnwnwsesenwnwwwnwnwe
seseseeneseeseseeseeseeseeeweese
sesesweeswseswsenweswseswnwsenwswswsw
sesweseeeeeeenwseswnewse
swwnwwnewwwwwwnwwwwwnwnwww
swswswneswswswswswswwswwwswwswwesw
wnewneneweneeneseswsenewnesweneene
eseeeseeeseenesw
sesenwseneseseseseswswswsesesewsesesesesw
nwneneneneswnenwnwnenenwneenenwnwnenwnene
neneenewnenenenenenenesweeeeeesee
nenwwswnwenwnwnwsesenenww
eenweswsweeeeneeneeweneene
nenewwneseenwnenwnwsenwnenwwnw
wwwnenewwsenesenwnwsewewwswswswnew
seswwswneswswswwnwswwswwswswswwswwsw
ewneneeeeenweesweswenweneneene
sweswsenwswswwswnewnenewswenweenw
sweweseesesesesewsenwseeweenesenwse
swnwnwwwwwwwne
nwnwswswseswswswswwswswswswswswse
seswseseswswseseseeseswnwswsenweswseneswse
eeswnweseeneeeeseewseseseseesesee
swswswswswswseswwswsweswswneswswwnenw
wnwenwwwwnwwwwwnwwnwwww
swwswwswswswswswwswwnwswswswswswswse
nwwwwwswnwwnwwnwwwwnwnwneww
eeneswenwnwswnwsweswswnwswnenenwnwse
swswseswswseswswswswneswswseneswseswswse
neeeeeeeeeeneneweweeeene
nwnwneenwnwnwnwswneswnenesenwswewnww
weswwswswnesewsewswswwneneseeese
wswswswseswswnesesesw
enwneswwnenwnewnenwnweenwnenwneswnesene
eswwswswswswswwswswswwswswswnweswswsw
eswsenweswswnwswswswswsewswwwnwswswsw
nenwnenenenenwnenenewneenenenenwnenene
wnesesenewwwsewwwnwnwwnenwwswnewsw
wwswswwswwswswwswswwnwswseswswswsw
neneneneneswnenwnenenenwnwswnenwswnenee
sesesesenesesenesewsesenewseswsesesese
wneewseswwwnewswswswswenwnewwww
swwnwswswswswnwswswswwsesweswswwesw
seseswseswseseswseswnweseseseseswseswse
swswseseswswswswsesweswnwseeseswnwsese
neswswnwnwsewnwenwwnwwweenwsewnw
ewneeneneenesweneeeneeenenenene
nwnwwnenwnwwnwnwnwsewnw
eeneneeseenweseswneesweneenenenw
neneneneeneneeneswnwnwneswnenenenenenenwne
nwneneswsewswnwsewwnenwewnw
nenwsenenwnenenenwnesenenenenenenenenwse
seeeesesenwseeesesewsewseeseese
nenenenenenenesesewnenwnenenenwnwnwnenw
neeneneeewneeneneneneeneenenenee
wswnwswseewnwnweneewwneww
seseenwseweswnwneenenenenwnwseeneswse
seswsenwswseeseseswswswseswswseswsesenwsw
neseeseswseswsesewswswnwswwseswnenwsesw
nwnenwswnenenwnwnwnwnwsenwnw
nwnwwswnwwenwnwwnewnwnwnwwnwnwsenwnw
seseeswseenwnwseneseeeesesewswsesese
neneswnwenwnenenenenenenwnenwnwnwnwnwnesw
swswswseeswneswswswswswsweswwneswswswnw
swseswswswswswswneeswwswwswswswseswsesw
sesesesewnwseseseseseseseeseseseseswsese
neenenwwenwswnwneswsweenwnw
wwnwwwnwwnwwnwnwnwseenwwnwnwnwnwnw
swneswsesweswswswswswswswswwwswwsw
esweeneeneeeneenesweeee
eeeeeenweesweeeeeeweew
seseswswewseswwseeswenwnwswseswswse
nenesesesweswnenwewseewnwseswewne
eseweseseseseeesesesesesesesesesee
sesenwswseeswswsesesesenwseseseeneseese
swnwswswnwnwsenwneenwwnwnenwwneenwe
nwwwwnwnwnwnwnwwnwnwnwswewwwnwwnw
seseswsewesesewseseseseseseeseswsesese
senwswwnwnenweesewswenenwneneswswwne
eseweneswsesewwnwwseseswswnesenesew
swwswswswswseswswswswsweswswsw
eesenweweseseeeeeeeseeseseese
seeeeneenewweeene
nenwswswseeewsewwnwwnwwwswwsenw
swswswswwwnewwswnwwnewwewewsww
sewwswswneeswwnwswwwswnewswwswswsw
swwewwnwswswswnwnwweswneeeeww
swswwswswseeseswneeweswswnwnwswene
newwnwseesewsesenwsewseewesenwene
wswwwnwwsenwwnewwnwsewwnwwne
swswseseswnweswnwneeswneswsesesenwwswnesw
nwnwnwnwwnwnwnwsenwnwwnwsenwnwnwwnenwnw
nwswwenwswsweswwswswwseswswswnwsesw
nwewwwnwwsenwwwnwesw
wnwnwnwnwnwwnwsenwnwneswnwenwwsenwnw
swnenwnwwnwnenwnenenwnenwnwenwnwenwnwsw
swswnwswsweswwseswnwwswswnwsenwswew
eeeeneeswseeeeeeeeeenenwene
neeeneneneeeneeeeneswneneenenee
nwnwnwwnwnwneenwnwnwnwsenenwnwnwnwnwnw
eeeseeeswseenwenenwseeseeeesw
neeneneeesenweeeene
neneenenenesenenenenenenenenenenenenwne
senwwswswwswswsewneseeseswneswswswswene
neeeeneeeseseeeeseeseeseesesww
eeeneneenewneneseneneneeeeneee
swnwwnwsenenwnenwnwsenwnwnenewnwenwne
neneneneneenenenenwnenenwwsenenenenenenw
wwnewwwseswwnewww
nwenesenwnwnwnwnew
swseseswseswseswswswenwswswseswseneswse
senwswsweseneeeeneeneeswnesewswwnw
eenenwswswnwswewwneenwwwwsewsenw
seeeenenwneneeneeeneeswe
newenweeneswneneswne
swswswseswswsenewwnwwwnwnesweswwww
nwneneeeneswneneneneeneeneeneeene
eeeeeeesweeeeewnweseeenw
swseswswswswswsewneswnwswswsesesesesesese
nwnwsenenenwswnwnenenwwsenenwnenewseswse
wsewswwswwwswwnewseenenenewwwse
nwnewnenenenenenwnenenenenenenwnenwsenw
wnwwwsenewwnwwwwwwwwwwww
nenwnenewseeseeswswenwwsesewsw
enwnenesweneneneneswenenwswneneeenenene
seeeeeenwnweeseeseeswseseeeee
wwnwwnwswwwwnwwnenesww
seswswswneseseseseswseseseswsesesesewswse
wnenwseseeseswswwseseswswswswseswswseswsw
wnwnwnwneenesenwnwnwnwnwnwnw
nenenenwneeneneneneneneswnenwnenenenenwne
sewwswswswwswswwswwswnwseswwswneswsw
eeeneeeswsenwwseseeeeeeeseese
swswswswswswneswswswswswwswswswsw
newswwswwnenwsewwwwwwwwwswsew
sesesesenwseseseseseseeseseswsenwsesese
swswsesweswwseswwswnwswswswswswwnwnw
nenenwneneswnenwsenewnesesewnwnewnee
sesesesesewneseseseneseseseseseseswsesee
nenenenenwwnesesenenenesesenewneenwene
wnwwwwsewnwswneenwwenwswwwwww
swseswswnwswswseswswswnwswswseseeswswswswsw
wnwwnwwnwwwnewwwnwwswwwwwsewe
neeeeneneenenenesewneneeneeenene
seneenweeneeeeeneenweeeeseee
enewnenwsenenwnenenenenesenwnenenwnenenw
neeneneswneneweenwneneeneeenenee
wwwswwswsweswneswswwswsewswswww
swwwswswseswwwswswwsenenwswwwwnw
neenwneneneeseswswewnwswnenwnenenwnenwne
seeseewwweeseweseeseeesesenwe
swneneneneneneneneneneneeneneneneenene
wwswseesweswneenenwnwseesewswnwene
seseseswseswswseswseneseseswswseswsesesew
neeneneseenewenenwswnweeneeswneswne
seswwneswsewnwnewsenwswswenwww
wwsewwwwwwwnewswwewwwwwww
nenenenwnenenenenenwnesenenenenenenenene
eseswswswwnwswneswneseeswswswswswswswww
neeesweenewenenweneneewnenenenene
nwswwwnwwewswwswwwswseswwwwswswsw
wwenwnwewswwwnenwwwnewnwswww
nwneenenwswwwsewewwsesewwsewswnw
seswseneswseeenenwseeseswneswsesesesenw
eeseswweseeseseesesesesenw
neseseseewwwneseseenwseseeseseeee
seswnwsweseseeswseseswnwnwsesesenweseswe
neseseswswswswsesesw
nenenenewnenwnwnesenenenenwnenwwneneenene
sweseseeswsesenweseesesewsesenwenesee
senenenenwwnwwnesenenesenenwnwnwnewnwe
swwnwseneswseseseneseseneseswnwnesewwswse
wnwnwnewnwnwwnwnwnwwsenwswwnwnenwwww
wnewwwnwwwwwsewwwwwwwnwwnw
eeesenwenesenweenwesweneeeeee
wsesenewnenenenenw
eeeeeseneeweneeeeeeeeee
eneseneweneneeeeswneeneeneneww
nwnwnwnwnwnwnwenwnwnwwewnwnw
seseseswswseseseswsesesewseseseseseswne
swwwsweswswswswwswswswswswneww
seeenweseweseesesweeeeeenwe
nweneneeneeeeeeeeneseeeneene
wswnewwwwwwwwswswwwswewwww
swswswseswswswwseseswneswseswseseswswsesw
swswswswseswswswsenwnweswswswseswsewesw
nwswnwwnwswnwnwnenwnwenenwsenwne
nwwnwesenwnwnwnenwwwnwnwewnwnwnwnwswnw
wswswswnwwwwwneswwswwsewwswwsw
nenewneneneeneewnenenenenenenwnenenene
nwseseswswseseseeeseeseneseseseseese
eswseeseseeewnwseeseseeeseseesese
nenwnwnwneneeneneneneneneneneneneneswnw
nwnenwneneneneenwnenenenenenenwnewnene
nwneneenenenwseeseneeneeenenenewnene
wneseswsweswswsenwswswswsweeswnwswnw
swneeswsewswswenweneswnwnesewew
nwnwnwnwnwnenwnwnwnwsenwsenwwnwnwnwnwnwne
neswneswnewneswseseswnwnwswnewseswsee
eenenwseweeneeneneeweneweeene
nenwwwnwnwneenenenwswnwnwswseenwswnwenw
sweswnwswsweeswwswnenw
wsewsewsenwneswnwnwwewswnwweenw
nenwnenwswnwnenwnwnenenwnenwnenwnenenene
swwneswwewwswneswwwswswwswwwse
swsewswwsewwswneswswwseneswswswnesw
seenenwsweesenwseswnweseeeeenwe
swwswwswswswweswnwsweswswswswnenwwwsw
wnwnwwswenwweswenwwwwwnwnwswnw
swswwswwwswwwwsewwwwwswswwnesw
neswswswswswswswwswswswswwswswswwwe
wenwenwwseswwwnewnwseseswwneswneww
nwswswswneswswwwsewwswswswswswsesww".split

require 'set'

# let orange = false and teal = true
# (I'm calling them "orange" and "teal" because I call adjacent tiles "neighbors" but then saying "white neighbor" and "black neighbor" was weird)
# all tiles start out orange
floor = Hash.new false

input.each { |line|
  x = 0.0
  y = 0.0
  i = 0
  until i == line.length

    # force the 6-direction space to fit a cartesian space:
    # let e/w be the positive/negative directions on the x axis
    # let n/s be the positive/negative directions on the y axis
    # let the size of any ne/se/sw/nw step be +/-1 y and +/-0.5 x
    # this means, for example, an 'nese' instruction is the same as just an 'e'
    case line[i]
    when 'e'
      x += 1
      i += 1
    when 'w'
      x -= 1
      i += 1
    when 'n'
      x += (line[i+1] == 'e') ? 0.5 : -0.5
      y += 1
      i += 2
    when 's'
      x += (line[i+1] == 'e') ? 0.5 : -0.5
      y -= 1
      i += 2
    end
  end

  # flip the tile at (x,y)
  floor[[x, y]] = ! floor[[x, y]]
}
# now we have the initial tile space

# rather than iterating over the sorta-infinite space and determining whether to flip each one,
# just look at the teal tiles and their neighbors, since they're what determines whether to flip:
# "Any teal tile with zero or more than 2 teal tiles immediately adjacent to it is flipped to orange.
#  Any orange tile with exactly 2 teal tiles immediately adjacent to it is flipped to teal."
# the neighbors of the tile at (x,y) are (x-0.5,y+1), (x+0.5,y+1), (x-1,y), (x+1,y), (x-0.5,y-1), (x+0.5,y-1)

(1..100).each do
  flip = Set.new

  # teal tiles only
  floor.select{ |_,v| v }.each{ |xy, tile|
    (x, y) = xy

    # count teal neighbors
    neighbors = [[x-0.5, y+1], [x+0.5, y+1], [x-1, y], [x+1, y], [x-0.5, y-1], [x+0.5, y-1]]
    count = neighbors.map{ |xa,ya| floor[[xa, ya]] }.count(true)

    # flip (teal) tile?
    flip.add(xy) if (count == 0 or count > 2)

    # now check tile's neighbors
    neighbors.each{ |xa, ya|
      next if flip.include? [xa, ya]

      # count teal neighbors
      neighborsa = [[xa-0.5, ya+1], [xa+0.5, ya+1], [xa-1, ya], [xa+1, ya], [xa-0.5, ya-1], [xa+0.5, ya-1]]
      counta = neighborsa.map{ |xb,yb| floor[[xb, yb]] }.count(true)

      # flip tile?
      flip.add([xa, ya]) if ((floor[[xa, ya]] and (counta == 0 or counta > 2)) or (! floor[[xa, ya]] and counta == 2))
    }
  }

  # flip em
  flip.each{ |xy| floor[xy] = ! floor[xy] }
end

# count the teal tiles
puts floor.values.count(true)
